Order Controller Created & Tested
nicole427/ePharmacyDeliverySystem pull request #178
Opened 2020-09-25 02:06 UTC by amahlathini

- Created controller for Order 
- Added relevant annotations
- Add a default constructor to the Order entity.
- Exposed all methods of that Order service including relevent business logic i.e. tracking order & getting completed orders for delivery.
- Finally, tested the Order controller

2020-09-25 06:14 UTC, nicole427 commented
Pull request has conflicts. Redo

2020-09-27 09:42 UTC, nicole427 requested changes
Remove target folder

2020-09-27 11:10 UTC, amahlathini commented
target folder removed

2020-09-27 11:11 UTC, nicole427 approved these changes

2020-09-27 11:11 UTC, merged